var inc=4;
console.log("pre increment",++inc);
console.log("without++",inc);
var bmc=4;
console.log("pre increment",++bmc);
console.log("without++",bmc);
var dbs=4;
console.log("pre increment",++dbs);
console.log("without++",dbs);
var sds=4;
console.log("pre increment",++sds);
console.log("without++",sds);
var inc=4;
console.log("post increment",inc++);
console.log("without++",inc);
var bmc=4;
console.log("post increment",bmc++);
console.log("without++",bmc);
var dbs=4;
console.log("post increment",dbs++);
console.log("without++",dbs);
var sds=4;
console.log("post increment",sds++);
console.log("without++",sds);
var inc=4;
console.log("pre decrement",--inc);
console.log("without--",inc);
var bmc=4;
console.log("pre decrement",--bmc);
console.log("without--",bmc);
var dbs=4;
console.log("pre decrement",--dbs);
console.log("without--",dbs);
var sds=4;
console.log("pre decrement",--sds);
console.log("without--",sds);
var inc=4;
console.log("post decrement",inc--);
console.log("without--",inc);
var bmc=4;
console.log("post decrement",bmc--);
console.log("without--",bmc);
var dbs=4;
console.log("post decrement",dbs--);
console.log("without--",dbs);
var sds=4;
console.log("post decrement",sds--);
console.log("without--",sds);